services:
  - type: web
    name: resume-parser-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn resume_parser_service:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: MAX_WORKERS
        value: 4
    autoDeploy: true
    healthCheckPath: /
