services:
  - type: web
    name: live-coding-hr-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MODEL_ENDPOINT
        value: https://0c09-34-60-0-20.ngrok-free.app # Your Colab ngrok URL
      - key: MONGODB_URI
        sync: false # This will be set in Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set in Render dashboard
      - key: JUDGE0_API_URL
        sync: false # This will be set in Render dashboard